sudo: required
dist: trusty

language: node_js
node_js:
- '12.19.0'

branches:
  only:
  - master

before_script:
- npm install -g @angular/cli
- npm install --silent

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

jobs:
  include:
  - stage: AngularJs Unit Tests
    env:
      - ANGULARJS_DIR=angularjs-demo
    script: cd $ANGULARJS_DIR && npm install --silent && npm run test-single-run
  - stage: AngularJs E2E Tests
    env:
      - ANGULARJS_DIR=angularjs-demo
    script: cd $ANGULARJS_DIR && npm install --silent && (npm start > /dev/null &) && (npm run e2e)
  - stage: Angular 6 Unit Tests
    env:
      - ANGULAR6_DIR=angular6-demo
    script: cd $ANGULAR6_DIR && npm install --silent && npm run test-single-run
  - stage: Angular 6 E2E Tests
    env:
      - ANGULAR6_DIR=angular6-demo
    script: cd $ANGULAR6_DIR && npm install --silent && (npm run e2e)
